config/routes.rb
Rails.application.routes.draw do

  get 'sessions/create'

  get 'sessions/destroy'
  get 'test/:firstname', to: 'sessions#test_login'

  get '/sessions/logout', to: 'sessions#log_out'
  get ':controler/sessions/logout', to: 'sessions#log_out'

  get  '/auth/shibboleth/callback', to: 'sessions#create'

  root :to => "projects#index"

  post '/ajax/creatorremove' => 'projects#creatorremove'
  post '/ajax/picadd' => 'projects#picadd'
  post '/ajax/getpicture' => "projects#getpic"

  post "projects/:id/createpic/" => 'projects#createpic'
  patch "projects/:id/createpic/" => 'projects#createpic'

  post "projects/preview" => "projects#preview"
  get 'projects/:id/managepictures' => "projectpictures#managepics"

  resources :projectpictures

  resources :profiles

  resources :projects

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
	has_many :userprojects, dependent: :destroy
	has_many :projects, through: :userprojects
	# callbacks
	before_save { email.downcase! if !email.nil?}

	validates :first_name, presence: true, length: { maximum: 25 }
	validates :last_name, presence: true, length: { maximum: 25 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
	#validates :email, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

	#for paperclip
	#has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	#validates_attachment_file_name :avater, :matches => [/jpe?g\z/, /gif\z/, /png\z/]

  	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	#validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  	validates_attachment_file_name :avatar, :matches => [/jpe?g\z/, /gif\z/, /png\z/]


  	#validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

#for oauth

  	#def self.from_omniauth(auth)
	#	where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
	#end

	def self.from_fakeuser(firstname)
		auth = { "provider" => "Test", "uid" => 0,
			"info" => {"firstname" => firstname, 'lastname' => 'Von Lastname', }}
		#this where may need to change
		where(first_name: firstname).first || create_from_omniauth(auth)
	end

	def self.create_from_omniauth(auth)
		create! do |profile|
			#provider should be just brandeis so I shouldnt need
			#profile.provider = auth["provider"]
			profile.uid = auth["uid"]
			profile.first_name = auth["info"]["firstname"]
			profile.last_name = auth["info"]["lastname"]
			profile.email = auth["info"]["email"]

 		end
 		#will haved to add other fields
	end


	# returns a users full name
	def full_name
		"#{first_name} #{last_name}"
	end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  #helper_method :collaborators
  helper_method :course_user_count, :collaborators


  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  #def update
  #  respond_to do |format|
  #    #on update if new pic not input dont erase the old may need a delete function of a default
  #    if profile_params[:avatar].nil?
  #      profile_params[:avatar] = @profile.avatar
  #    end
  #    if @profile.update(profile_params)
  #      format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
  #      format.json { render :show, status: :ok, location: @profile }
  #    else
  #      format.html { render :edit }
  #      format.json { render json: @profile.errors, status: :unprocessable_entity }
  #    end
  #  end
  #end

  respond_to :html, :json
  def update
    @profile.update_attributes(profile_params)
    respond_with @profile
  end


  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def collaborators
    collaborators = Hash.new
    @profile.projects.each do |project|
      project.profiles.each do |profile|
        if (profile != @profile)
          collaborators[profile] = 1
        end
      end
    end
    return collaborators
  end

  def course_user_count
    return 1
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :bio, :email, :image_url, :avatar)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<script type="text/javascript">
  function removecreator(button, projectid) {
    var r = confirm("Arou you sure you no longer with to be associated with this project?");
    if (r == true) {

      $.post('/ajax/creatorremove.json', {
             p: projectid
        }, function(data) {
             var output = data.result;
             alert(output);
             $(button).closest("li").hide();
        })
    }

  }
</script>
<div class="col-xs-11 col-xs-offset-1">
    <h4 class="turninline-block">

      <div class="field turninline-block">
        <%= f.label :first_name%>
        <%= f.text_field :first_name, :class => "form_control" %>
      </div>
      <div class="field turninline-block">
        <%= f.label :last_name%>
        <%= f.text_field :last_name, :class => "form_control" %>
      </div>
    </h4>
    <div class="actions turninline-block">
      <%= f.submit %>
    </div>
</div>

<div class="col-xs-11 col-xs-offset-1">
  <div class="col-lg-4 col-sm-6" >
    <div id="picdiv" >
      <%= image_tag @profile.avatar.url(:medium), :class => "img-responsive" %>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
       <h3 class="panel-title">Change profile picture</h3>
      </div>
      <div class="panel-body">
        <div class="field">
          <%= f.file_field :avatar %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-8 col-sm-6 container">
    <div class="panel panel-primary">
      <div class="panel-heading">
       <h3 class="panel-title">Contact Info</h3>
      </div>
      <div class="panel-body">
        <div class="field">
          <%= f.label :email %>
          <%= f.text_field :email %>
        </div>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Bio</h3>
      </div>
      <div class="panel-body">
        <div class="field">
          <%= f.text_area :bio, :class => "form_control col-xs-12 custom-control", :rows => '5' %>
        </div>
      </div>
    </div>
  </div>
</div>

<div  class="col-xs-11 col-xs-offset-1">

  <div  id="projectspanel" class="col-sm-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Projects</h3>
      </div>
      <div class="panel-body">
        <ul class="list-group ">
          <% @profile.projects.each do |profproj| %>
              <li class="list-group-item">
                <%if profproj.projectpictures.first%>
                <div class="turninline-block">
                  <%= image_tag profproj.projectpictures.first.picture.url(:thumb), :class => 'img-responsive'%>
                </div>
                <%end%>
                <h5 class="turninline-block">
                  <%=profproj.title%>
                </h5>
              </li>
          <%end%>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="panel panel-primary ">
      <div class="panel-heading">
        <h3 class="panel-title">Collaborators</h3>
      </div>
      <div class="panel-body">
        <ul class="list-group ">
          <% count = course_user_count %>
          <% collab = collaborators %>
          <% collab.keys.each do |profile| %>
              <li class="list-group-item">
               <%if profile.avatar%>
               <div class="turninline-block">
               <%= image_tag profile.avatar.url(:thumb), :class => 'img-responsive'%>
                </div>
                <%end%>
                <h5 class="turninline-block">
                  <%=profile.full_name%>
                </h5>
              </li>
          <%end%>
        </ul>
      </div>
    </div>
  </div>


</div>

<% end %>

app/views/profiles/_indexedprofile.html.erb
<%#can write on on click script to redirect to the project%>
<a href=<%= profile_path(profile)%>>
  <div id="<%= profile.id %>" class="col-lg-2 col-md-3 col-sm-3 col panel panel-default square" >
    <div class="imageheight">
      <% displayedpicture = profile.avatar%>
      <%if !displayedpicture.nil?%>
        <%= image_tag displayedpicture.url(), :class => 'fisrtpic img-responsive', :onload => "trimImage(\"##{profile.id}\")"%>
      <%end%>
    </div>
    <h4 class="title text-center">
      <%=profile.full_name%>
    </h4>
  </div>
</a>

app/views/profiles/edit.html.erb
<div class="col-xs-11 col-xs-offset-1">
	<h1 class="turninline-block">Editing profile</h1>
	<h4 class="turninline-block">
    <%= link_to "back", @profile%>
	</h4>
</div>

<%= render 'form' %>

app/views/profiles/index.html.erb
<script type="text/javascript">

$(document).ready(function() {
    squarifyMe('.square');
});
</script>


<div id="project_list" >
  <div class="col-xs-11 col-xs-offset-1">
  <h1>Listing profiles</h1>
    <% @profiles.each do |profile| %>
      <%=render partial: "profiles/indexedprofile", object: profile, as: "profile"%>
    <% end %>
  </div>

</div>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-xs-11 col-xs-offset-1">

      <h1 class="turninline-block">
        <strong>
        <%= @profile.first_name + " " +@profile.last_name %>
        </strong>
      </h1>
    <% if current_user == @profile %>

      <span class="bottom_right">
      <%= link_to 'Edit', edit_profile_path(@profile) %>
      |
      <%= link_to 'Destroy', @profile, method: :delete, data: { confirm: 'Are you sure?' } %>
      </span>
    <% end %>
</div>

<div class="col-xs-11 col-xs-offset-1">
  <div id="picdiv" class="col-lg-4 col-sm-6" >
    <%= image_tag @profile.avatar.url(), :class => "img-responsive"%>
  </div>
  <div class="col-lg-8 col-sm-6 container">
    <div class="panel panel-success">
      <div class="panel-heading">
       <h3 class="panel-title">Contact Info</h3>
      </div>
      <div class="panel-body">
       <%= @profile.email %>
      </div>
    </div>

    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title">Bio</h3>
      </div>
      <div class="panel-body">
        <%= @profile.bio %>
      </div>
    </div>
  </div>
</div>

<div  class="col-xs-11 col-xs-offset-1">

  <div  id="projectspanel" class="col-sm-6">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title">Projects</h3>
      </div>
      <div class="panel-body">
        <ul class="list-group ">
          <% @profile.projects.each do |profproj| %>
            <a href=<%=project_path(profproj)%>>
              <li class="list-group-item">
                <%if profproj.projectpictures.first%>
                <div class="turninline-block">
                  <%= image_tag profproj.projectpictures.first.picture.url(:thumb), :class => 'img-responsive'%>
                </div>
                <%end%>
                <h5 class="turninline-block">
                  <%=profproj.title%>
                </h5>
              </li>
            </a>
          <%end%>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="panel panel-success ">
      <div class="panel-heading">
        <h3 class="panel-title">Collaborators</h3>
      </div>
      <div class="panel-body">
        <ul class="list-group ">
          <% count = course_user_count %>
          <% collab = collaborators %>
          <% collab.keys.each do |profile| %>
            <a href=<%=profile_path(profile)%>>
              <li class="list-group-item">
               <%if profile.avatar%>
               <div class="turninline-block">
               <%= image_tag profile.avatar.url(:thumb), :class => 'img-responsive'%>
                </div>
                <%end%>
                <h5 class="turninline-block">
                  <%=profile.full_name%>
                </h5>
              </li>
            </a>
          <%end%>
        </ul>
      </div>
    </div>
  </div>

</div>