config/routes.rb
Rails.application.routes.draw do

  get 'sessions/create'

  get 'sessions/destroy'
  get 'test/:firstname', to: 'sessions#test_login'

  get '/sessions/logout', to: 'sessions#log_out'
  get ':controler/sessions/logout', to: 'sessions#log_out'

  get  '/auth/shibboleth/callback', to: 'sessions#create'

  root :to => "projects#index"

  post '/ajax/creatorremove' => 'projects#creatorremove'
  post '/ajax/picadd' => 'projects#picadd'
  post '/ajax/getpicture' => "projects#getpic"

  post "projects/:id/createpic/" => 'projects#createpic'
  patch "projects/:id/createpic/" => 'projects#createpic'

  post "projects/preview" => "projects#preview"
  get 'projects/:id/managepictures' => "projectpictures#managepics"

  resources :projectpictures

  resources :profiles

  resources :projects

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :userprojects, dependent: :destroy
	has_many :projectpictures, dependent: :destroy
	#if no users project should desrtoy not sure how of if want to do this
	has_many :profiles, through: :userprojects

	validates :title, presence: true, length: { maximum: 25 }
	#for paper clip
	#has_attached_file :paperclippicture, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	#validates_attachment_content_type :paperclippicture, :content_type => /\Aimage\/.*\Z/


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy,]
  helper_method :otherprojects

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    if !newprojectpicture_params[:picture].nil? || !(newprojectpicture_params[:description] == "")
      @projectpicture = Projectpicture.new(newprojectpicture_params)
      @projectpicture.project = @project
    end

      if logged_in?
        respond_to do |format|
          if @project.save
            @userproject = Userproject.create!(profile: current_user, project: @project)
            if @projectpicture
              if @projectpicture.save

              else
                format.html { render :new }
                format.json { render json: @projectpicture.errors, status: :unprocessable_entity }
              end
            end
            format.html { redirect_to @project, notice: 'Project was successfully created.' }
            format.json { render :show, status: :created, location: @project }
          else
            format.html { render :new }
            format.json { render json: @project.errors, status: :unprocessable_entity }
          end
        end
      else
        ActiveSupport::Notifications.instrument('render', extra: :information) do

        render :new
        end
         flash[:alert] = "You must be signed in to create a project"
      end
  end

  respond_to :html, :json
  def update

    if @project.update_attributes(project_params)
       flash[:alert] = "project successfully updated"
    else
       flash[:alert] = "project failed to update"
    end
    respond_with @project
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end

  end

  def otherprojects
    otherprojects = Hash.new
    @project.profiles.each do |profile|
     profile.projects.each do |project|
        if (project != @project)
          otherprojects[project] = 1
        end
      end
    end
    return otherprojects
  end

  # POST /ajax/creatorremove
  def creatorremove

    result = params["p"].to_i
    project = Project.where(:id => params["p"].to_i).first
    if project.profiles.include?(current_user)

      respond_to do |format|
        if project.profiles.delete(current_user)
          format.json {render :json => {:result => "Creater successfully removed"}}
        else

        end
      end
    end
  end


  def getpic
    pic = Projectpicture.where(:id => params["pid"].to_i).first
    respond_to do |format|
        format.json {render :json => {:description => pic.description}}
    end
  end

  def createpic
    binding.pry
    projectpicture = Projectpicture.new(projectpicture_params)
    @project = Project.where(:id => params["id"].to_i).first
    projectpicture.project = @project

      if projectpicture.save
        render partial: "projects/thumbnailbar", object: @project, as: "project"
        else

      end

  end

  #this is the ajax submision for pictures fomr the modal to work probably need to tweek response
  #currently doesnt render if there is a picture as an ajax success not returned or something
   def preview
    @project = Project.where(:id => params["id"].to_i).first
    projectpicture = Projectpicture.new(projectpicture_params)
    description = params["description"].values.first
    binding.pry
    if params["projectpicture"]
      picture = params["projectpicture"].values.first
      projectpicture = Projectpicture.new(description: description, picture: picture)
    else
      projectpicture = Projectpicture.new(description: description)
    end
    projectpicture.project = @project
    if projectpicture.save
      binding.pry
      render partial: "projects/thumbnailbar", object: @project, as: "project"
    else
      render status: :internal_server_error
    end
  end


  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def projectpicture_params
      #params.require(:projectpicture).permit(:picture, :description)
      params.permit("picture", "description")
    end
    def newprojectpicture_params
      params.require(:projectpicture).permit(:picture, :description,)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :image_url, :embedcode, :images)
      #not sure if I want to allow scripts the potential for disaster is huge but gist uses it

    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>

  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%#store project in session for picture to use%>
<%session[:project] = @project.id%>

<script type="text/javascript">
  window.onresize = function() {
    resizepicturearea();
  }
</script>


<%if @project.id%>
<script type="text/javascript">
  function removecreator() {
    var r = confirm("Are you sure you no longer with to be associated with this project?");
    if (r == true) {

      $.post('/ajax/creatorremove.json', {
             p: <%=@project.id%>
        }, function(data) {
             var output = data.result;
             alert(output);
             window.location.replace("<%=project_url(@project)%>");
        })
    }

  }
</script>
<%end%>

  <div class="col-xs-11 col-xs-offset-1">
    <h1 class="turninline-block" style="margin:20px; margin-left:0px">
      <%= f.label :title %>
      <strong>
        <%= f.text_field :title %>
      </strong>
    </h1>
      <%= f.submit %>
  </div>
<div class="col-xs-7 col-xs-offset-1 container">
    <div class="row">
      <div id="mainpic" class="col-md-6">
        <% displayedpicture = @project.projectpictures.first%>
        <%if !displayedpicture.nil?%>
        <%= image_tag displayedpicture.picture.url(), :class => 'fisrtpic img-responsive', :onload => 'resizepicturearea()'%>
        <%end%>
      </div>
      <div class="col-md-4 col-xs-8">

        <div id="picdescpanel" class="panel panel-primary">
          <div id='picdescpanelhead' class="panel-heading">
            <h3 class="panel-title">Picture Description</h3>
          </div>
          <div id='picdescpanelbody' class="panel-body scrollable">
            <%if !displayedpicture.nil?%>
              <%= displayedpicture.description %>
            <%end%>
          </div>
        </div>

      </div>
      <div id="thumbnaildiv" class="col-md-2 col-xs-4 panel panel-primary">
        <!-- Button trigger modal -->
        <!--
        <button id="addpicbutton" type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
          add picture
        </button>
        <br>
        -->
        <div id="update-container">
          <%=render partial: "projects/thumbnailbar", object: @project, as: "project"%>
        </div>
      </div>
    </div>
  <br>
  <br>

  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Embedcode</h3>
    </div>
    <div class="panel-body">
      <%= f.text_area :embedcode, :class => "form_control col-xs-12", :rows => '3' %>
  </div>

  </div>
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Project Description</h3>
    </div>
    <div class="panel-body">
      <%= f.text_area :description, :class => "form_control col-xs-12", :rows => '15' %>
    </div>
  </div>

</div>


<div class="col-xs-3 col-xs-offset-1 container">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Creators</h3>
    </div>
    <div class="panel-body">
      <ul class="list-group">
        <% @project.profiles.each do |profile| %>
          <li class="list-group-item">
            <%if profile.avatar%>
              <div class="turninline-block">
              <%= image_tag profile.avatar.url(:thumb), :class => "img-responsive"%>
              </div>
            <%end%>
            <%=profile.full_name%>
            <%if current_user == profile%>
              <button type="button" onclick="removecreator()">Remove from project</button>
            <%end%>
          </li>
        <%end%>
      </ul>
    </div>
  </div>
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Other projects by the creators</h3>
    </div>
    <div class="panel-body">
      <ul class="list-group">
        <%projects = otherprojects%>
        <% projects.keys.each do |project| %>
          <li class="list-group-item">
            <% pic = project.projectpictures.first%>
            <% if !pic.nil? && !pic.picture.nil? %>
              <div class="turninline-block">
              <%= image_tag pic.picture.url(:thumb), :class => "img-responsive"%>
              </div>
            <%end%>
            <%=project.title%>
          </li>
        <%end%>
      </ul>
    </div>
  </div>
</div>

<% end %>


<!-- Modal  for ajax submission the return doesnt work right-->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">

      <%pic = Projectpicture.new%>

        <%= form_for(@project, format: 'js', :url => url_for(:controller => 'projects', :action => 'createpic'), remote: true, :authenticity_token => true, :html => {:id => "pictureform"}) do |p| %>
          <%= hidden_field_tag :id, @project.id %>
                  <h4>
                    <strong>Picture</strong>
                  </h4>
          <%= p.file_field :picture, id: "pictureinput" %>
          <br>
          <h4>
            <strong>Picture Description</strong>
          </h4>
          <%= p.text_area :description, :class => "form_control col-xs-12 custom-control", :rows => '10', :id => "descriptioninput"%>
          <%#= p.submit :id => "submitbutton"%>
          <%=p.submit "Save", :disable_with=>"Loading..."%>
        <%end%>

      <%= form_tag({:action => 'preview'}, :format => 'js', :remote => true, :'data-update-target' => 'update-container', :authenticity_token => true) do %>
           <%= hidden_field_tag :id, @project.id %>
                  <h4>
                    <strong>Picture</strong>
                  </h4>
          <%= file_field :projectpicture, :picture %>
          <br>
          <h4>
            <strong>Picture Description</strong>
          </h4>
          <%= text_area :description, :class => "form_control col-xs-12 custom-control", :rows => '10', :id => "descriptioninput"%>
          <%= submit_tag 'Submit', :disable_with => 'Please wait...', :class => 'submit' %>

      <% end %>

    </div>
      <div class="modal-footer">
        <br>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/projects/_indexedproject.html.erb
<%#can write on on click script to redirect to the project%>
<a href=<%= project_path(project)%>>
	<div id="<%= project.id %>" class="col-lg-2 col-md-3 col-sm-3 col panel panel-default square" >
		<div class="imageheight">
			<% displayedpicture = project.projectpictures.first%>
			<%if !displayedpicture.nil?%>
				<%= image_tag displayedpicture.picture.url(), :class => 'fisrtpic center-img img-responsive', :onload => "trimImage(\"##{project.id}\")"%>
			<%end%>
		</div>
		<h4 class="title text-center">
			<%=project.title%>
		</h4>
	</div>
</a>

app/views/projects/_preview.html.erb
<ul id='thumbnailbar' class="list-group scrollable">
	<% project.projectpictures.each do |projectpicture| %>
		<li class="list-group-item">
			<%= image_tag projectpicture.picture.url(:thumb), :onclick => "swappictures( '#{image_tag projectpicture.picture.url(:medium), :class => 'fisrtpic', :onload => 'resizepicturearea()'}', '#{projectpicture.description}')"%>
		</li>
	<%end%>
</ul>

app/views/projects/_thumbnailbar.html.erb
<script type="text/javascript">
	function swappictures(imagesrc, picid) {
		var mainpic = $('#mainpic');
		var picdescpanelbody = $('#picdescpanelbody');

		$.post('/ajax/getpicture.json', {
            pid: picid
        }, function(data) {
            var description = data.description;
            var image = data.image;
			picdescpanelbody.html(description);
			mainpic.html(imagesrc);
        })

	}
</script>

<div id="thumbcontainer">
	<ul id='thumbnailbar' class="list-group scrollable">
		<% project.projectpictures.each do |projectpicture| %>
		  <li class="list-group-item">
		    <%= image_tag projectpicture.picture.url(:thumb), :class =>'center-img img-responsive', :onclick => "swappictures( '#{image_tag projectpicture.picture.url(), :class => 'fisrtpic img-responsive', :onload => 'resizepicturearea()'}', #{projectpicture.id})"%>

          </li>
        <%end%>
	</ul>
</div>

app/views/projects/edit.html.erb
<div class="col-xs-11 col-xs-offset-1">
	<h1 class="turninline-block">
		<strong>
			Editing Project
		</strong>
	</h1>
	<h3 class="turninline-block" style="padding-left: 20px; padding-right:20px; margin:0px">
    	<%= link_to 'back', @project%>
	</h3>

</div>

<%= render 'form' %>

app/views/projects/index.html.erb
<script type="text/javascript">

$(document).ready(function() {
    squarifyMe('.square');
});
</script>


<div id="project_list" >
  <div class="col-xs-11 col-xs-offset-1">
  <h1>Listing projects</h1>
    <% @projects.each do |project| %>
      <%=render partial: "projects/indexedproject", object: project, as: "project"%>
    <% end %>
  </div>

</div>

app/views/projects/new.html.erb
<div class=" col-xs-offset-1 turninline-block">
	<h1>
		<strong>
			New project
		</strong>
	</h1>
</div>
<p id="notice"><%= notice %></p>
<% if flash[:alert] %>
    <p class="flash-error"><%= flash[:alert] %></p>
<% end %>

<%= form_tag({:action => 'create'}, :multipart => true) do%>

  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-xs-11 col-xs-offset-1 pull-left">
    <h1 class="turninline-block">
      <%= label :project, :title %><br>
      <strong>
        <%= text_field :project, :title %>
      </strong>
    </h1>
      <button type="submit">Create</button>
  </div>

<div class="col-xs-11 col-xs-offset-1 container">
  <h3>
    <strong>Picture</strong>
  </h3>

  <div class="row">
    <div id="mainpic" class="col-sm-6">
    	<div class="panel panel-default">
      <div class="panel-heading">
       <h3 class="panel-title">Add first picture</h3>
      </div>
      <div class="panel-body">
        <div class="field">
	    	<%= file_field :projectpicture, :picture %>
        </div>
      </div>
    </div>
    </div>
    <div class="col-sm-6">

      <div id="picdescpanel" class="panel panel-default">
        <div id='picdescpanelhead' class="panel-heading">
          <h3 class="panel-title">Picture Description</h3>
        </div>
        <div id='picdescpanelbody' class="panel-body scrollable">
    		<%= text_area :projectpicture, :description, :class => "form_control col-xs-12 custom-control", :rows => '10', :id => "descriptioninput"%>

        </div>
      </div>

    </div>

  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Embedcode</h3>
    </div>
    <div class="panel-body">
      <%= text_area :project, :embedcode, :class => "form_control col-xs-12", :rows => '3' %>
  </div>

  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Description</h3>
    </div>
    <div class="panel-body">
      <%= text_area :project, :description, :class => "form_control col-xs-12", :rows => '15' %>
    </div>
  </div>

</div>

<% end %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>
<% if flash[:alert] %>
    <p class="flash-error"><%= flash[:alert] %></p>
<% end %>

<script type="text/javascript">
	window.onresize = function() {
		resizepicturearea();
	}
</script>

<div class="col-xs-11 col-xs-offset-1 pull-left">
		<h1 class="turninline-block">
			<strong>
				  <%= @project.title %>
			</strong>
		</h1>

		<% if @project.profiles.include?(current_user)%>
		<span class="bottom_right">
	  		<%= link_to 'Edit', edit_project_path(@project) %>
	  	</span>
		<% end %>
</div>

<div class="col-xs-7 col-xs-offset-1 container">
  <div class="row">
   	<% displayedpicture = @project.projectpictures.first%>
   	<%if !displayedpicture.nil?%>
    	<div id="mainpic" class="col-md-6">
    	  <%= image_tag displayedpicture.picture.url(), :class => 'fisrtpic img-responsive ', :onload => 'resizepicturearea()'%>
    	</div>
    	<div class="col-md-4 col-xs-8">
    	  <div id="picdescpanel" class="panel panel-primary">
    	    <div id='picdescpanelhead' class="panel-heading">
    	      <h3 class="panel-title">Picture Description</h3>
    	    </div>
    	    <div id='picdescpanelbody' class="panel-body scrollable">
    	        <%= displayedpicture.description %>
    	    </div>
    	  </div>
    	</div>

		<div id="thumbnaildiv" class="col-md-2 col-xs-4 panel panel-primary">
			<% if @project.profiles.include?(current_user)%>
				<a href=<%= project_path(@project)+"/managepictures"%>>
        			<button id="addpicbutton" type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
          			<span style="font-size:smaller;">Manage pictures</span>
        			</button>
        		</a>
        		<br>
        	<%end%>
        	<div id="update-container">
         		<%=render partial: "projects/thumbnailbar", object: @project, as: "project"%>
        	</div>
      </div>

    <%end%>
  </div>

  	<%#by default it saves a space not sure why%>
	<%if !@project.embedcode.nil? && !(@project.embedcode == "") %>
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h3 class="panel-title">Embed</h3>
		</div>
		<div class="panel-body">
			<div class="embed-responsive embed-responsive">
				<%tags = %w(a acronym b strong i em li ul ol h1 h2 h3 h4 h5 h6 blockquote br cite sub sup ins p iframe)%>
				<%attributes = %w(href title class id width height src frameborder allowfullscreen)%>
				<%=sanitize( @project.embedcode, tags: tags, attributes: attributes).html_safe%>
			</div>
		</div>
	</div>
	<%end%>


	<div class="panel panel-primary">
		<div class="panel-heading">
			<h3 class="panel-title">Project Description</h3>
		</div>
		<div class="panel-body">
			<%= @project.description %>
		</div>
	</div>

</div>


<div class="col-xs-3 col-xs-offset-1 container">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h3 class="panel-title">Creators</h3>
		</div>
		<div class="panel-body">
			<ul class="list-group">
				<% @project.profiles.each do |profile| %>
					<a href=<%= profile_path(profile)%>>
						<li class="list-group-item">
							<%if profile.avatar%>
								<div class="turninline-block">
              						<%= image_tag profile.avatar.url(:thumb), :class => "img-responsive"%>
              					</div>
							<%end%>
							<%= profile.full_name%>
						</li>
					</a>
				<%end%>
			</ul>
		</div>
	</div>
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h3 class="panel-title">Other projects by the creators</h3>
		</div>
		<div class="panel-body">
			<ul class="list-group ">
				<%projects = otherprojects%>
				<% projects.keys.each do |project| %>
					<a href=<%= project_path(project)%>>
						<li class="list-group-item">
							<% pic = project.projectpictures.first%>
							<% if !pic.nil? && !pic.picture.nil? %>
								<div class="turninline-block">
								<%= image_tag pic.picture.url(:thumb), :class => "img-responsive"%>
								</div>
							<%end%>
							<%=project.title%>
						</li>
					</a>
				<%end%>
			</ul>
		</div>
	</div>
</div>