config/routes.rb
Rails.application.routes.draw do

  get 'sessions/create'

  get 'sessions/destroy'
  get 'test/:firstname', to: 'sessions#test_login'

  get '/sessions/logout', to: 'sessions#log_out'
  get ':controler/sessions/logout', to: 'sessions#log_out'

  get  '/auth/shibboleth/callback', to: 'sessions#create'

  root :to => "projects#index"

  post '/ajax/creatorremove' => 'projects#creatorremove'
  post '/ajax/picadd' => 'projects#picadd'
  post '/ajax/getpicture' => "projects#getpic"

  post "projects/:id/createpic/" => 'projects#createpic'
  patch "projects/:id/createpic/" => 'projects#createpic'

  post "projects/preview" => "projects#preview"
  get 'projects/:id/managepictures' => "projectpictures#managepics"

  resources :projectpictures

  resources :profiles

  resources :projects

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gallery</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%#= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
   <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css">
</head>

<body>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active navitempadding">
			<%= link_to 'Projects', projects_path%>
		</li>
        <li class="active navitempadding">
			<%= link_to 'Profiles', profiles_path%>
		</li>
       	<li class="active navitempadding">
			<%#this is to disable the button if it  not logged in check allert script runs the popup%>
			<%= link_to_if(logged_in?, 'New project', new_project_path, class: "usercheck")  do
				link_to('New project', "", class: "usercheck")
			end%>
		</li>
      </ul>
      <!-- if you want to add a search bar
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
	  -->
      <ul class="nav navbar-nav navbar-right">
		<% if logged_in? %>
      		<li class="active">
				<%= link_to current_user.first_name, profile_path(current_user)%>
			</li>

			<li class="dropdown active">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					<b class="caret"></b>
				</a>
				<ul class="dropdown-menu">
					<li><a href='sessions/logout' >log out</a></li>
				</ul>
			</li>
		<%else%>
      		<li class="active">
				<%= link_to 'log in', root_path%>
			</li>
		<%end%>
	  </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

	<%= yield %>

	<%= javascript_tag "UserCheckAlert(#{logged_in?})" %>
 	<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
</body>
</html>